import pytest
from shop import (
    ITEMS,
    ITEM_KEYS,
    ITEM_INDEX_MAP,
    INDEX_ITEM_MAP,
    CAT_INDEX_MAP,
    INDEX_CAT_MAP,
    get_item_by_ref,
    get_item_ref,
    resolve_item_id,
    DICTORS_ORDER,
)
from pets import PETS_SHOP


def test_items_indexing_integrity():
    assert len(ITEM_KEYS) == len(ITEMS)
    assert len(ITEM_INDEX_MAP) == len(ITEMS)
    assert len(INDEX_ITEM_MAP) == len(ITEMS)

    for item_id in ITEMS:
        ref = get_item_ref(item_id)
        resolved = get_item_by_ref(ref)
        assert resolved == item_id, f"Failed ref resolution for {item_id}"


def test_dictors_order_completeness():
    assert len(DICTORS_ORDER) == 70
    assert DICTORS_ORDER[0] == "dictor_common"
    assert DICTORS_ORDER[69] == "dictor_antigravity"

    # Test resolving by number
    assert resolve_item_id("1") == "dictor_common"
    assert resolve_item_id("70") == "dictor_antigravity"
    assert resolve_item_id("35") == "dictor_phoenix"


def test_item_aliases_resolution():
    cases = {
        "bmw": "бмв",
        "BMW": "бмв",
        "gelik": "гелик",
        "гелик": "гелик",
        "bugatti": "бугатти",
        "bunker": "sec_bunker",
        "бункер": "sec_bunker",
        "vip": "вип",
        "вип": "вип",
        "medkit": "medkit",
        "аптечка": "medkit",
        "priora": "лада",
        "приора": "лада",
        "camry": "камри",
        "семечки": "семечки",
        "антигравити": "dictor_antigravity",
        "antigravity": "dictor_antigravity",
        "ковчег": "kovcheg",
        "майнер": "prestige_mine",
    }
    for query, expected in cases.items():
        resolved = resolve_item_id(query)
        assert resolved == expected, f"Failed to resolve query '{query}': got {resolved}, expected {expected}"


def test_admin_callback_data_length_under_64_bytes():
    """
    CRITICAL: Telegram has a hard limit of 64 bytes for inline button callback_data.
    Verify that ALL callbacks generated by the admin inventory system NEVER exceed 64 bytes.
    """
    long_chat_id = -1002444654321  # 14 chars
    long_target_id = 9876543210    # 10 chars
    max_page = 99

    for item_id in ITEMS:
        item_idx = ITEM_INDEX_MAP[item_id]
        cat = ITEMS[item_id].get("cat", "other")
        cat_code = CAT_INDEX_MAP.get(cat, 0)

        # 1. Increment button
        cb_plus = f"db_pich_{long_chat_id}:{long_target_id}:p:{max_page}:{item_idx}"
        assert len(cb_plus.encode("utf-8")) <= 64, f"cb_plus exceeded 64 bytes: {cb_plus} ({len(cb_plus.encode('utf-8'))} bytes)"

        # 2. Decrement button
        cb_minus = f"db_pich_{long_chat_id}:{long_target_id}:m:{max_page}:{item_idx}"
        assert len(cb_minus.encode("utf-8")) <= 64, f"cb_minus exceeded 64 bytes: {cb_minus} ({len(cb_minus.encode('utf-8'))} bytes)"

        # 3. Custom quantity prompt button
        cb_qty = f"db_piq_{long_chat_id}:{long_target_id}:{item_idx}"
        assert len(cb_qty.encode("utf-8")) <= 64, f"cb_qty exceeded 64 bytes: {cb_qty} ({len(cb_qty.encode('utf-8'))} bytes)"

    # Category navigation buttons
    for cat_code in range(len(CAT_INDEX_MAP)):
        cb_cat = f"db_pic_{long_chat_id}:{long_target_id}:{max_page}:{cat_code}"
        assert len(cb_cat.encode("utf-8")) <= 64, f"cb_cat exceeded 64 bytes: {cb_cat}"

        cb_give_all = f"db_pial_{long_chat_id}_{long_target_id}_{cat_code}"
        assert len(cb_give_all.encode("utf-8")) <= 64, f"cb_give_all exceeded 64 bytes: {cb_give_all}"

        cb_clear_cat = f"db_picl_{long_chat_id}_{long_target_id}_{cat_code}"
        assert len(cb_clear_cat.encode("utf-8")) <= 64, f"cb_clear_cat exceeded 64 bytes: {cb_clear_cat}"


def test_pets_shop_completeness():
    required_pets = {"hamster", "cat", "dog", "fox", "dragon", "unicorn"}
    assert required_pets.issubset(set(PETS_SHOP.keys()))

    # Verify pet admin buttons length <= 64 bytes
    long_chat_id = -1002444654321
    long_target_id = 9876543210
    for p_id in PETS_SHOP:
        cb_pet = f"db_ppet_act_{long_chat_id}_{long_target_id}_set_{p_id}"
        assert len(cb_pet.encode("utf-8")) <= 64, f"cb_pet exceeded 64 bytes: {cb_pet}"


def test_cards_system_and_callbacks():
    import json
    import cards_system
    assert len(cards_system.CARDS) == 200
    assert "meme_1" in cards_system.CARDS
    assert "meme_200" in cards_system.CARDS

    long_chat_id = -1002444654321
    long_target_id = 9876543210
    for cid in cards_system.CARDS:
        cb_card = f"db_pcard_ch_{long_chat_id}:{long_target_id}:p:0:{cid}"
        assert len(cb_card.encode("utf-8")) <= 64, f"cb_card exceeded 64 bytes: {cb_card}"


def test_diseases_and_compound_callbacks():
    from diseases import DISEASES
    assert "syphilis" in DISEASES
    assert "gonorrhea" in DISEASES

    long_chat_id = -1002444654321
    long_target_id = 9876543210
    for d_id in list(DISEASES.keys()) + ["fullhouse"]:
        cb_dis = f"db_pdis_inf_{long_chat_id}_{long_target_id}_{d_id}"
        assert len(cb_dis.encode("utf-8")) <= 64, f"cb_dis exceeded 64 bytes: {cb_dis}"


def test_creator_commands_registered():
    import creator
    handler_names = [h.callback.__name__ for h in creator.router.message.handlers]
    assert "cmd_give_item" in handler_names
    assert "cmd_del_item" in handler_names
    assert "cmd_setmoney" in handler_names
    assert "cmd_setbank" in handler_names
    assert "cmd_give_card" in handler_names
    assert "cmd_give_all_cards" in handler_names
    assert "cmd_creator_heal" in handler_names
    assert "cmd_creator_infect" in handler_names
    assert "cmd_set_prestige" in handler_names

